apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
commonLabels:
 variant: products
resources:
#bases:
- ../../base
patches:
- path: ./replicas.yaml
- path: ./nodeport.yaml
images:
 - name: nginx
   newTag: 1.9.0
